### ISSUE TITLE
error when running demo.py  and model_test.py  

### ISSUE THREAD

**Issue by BackT0TheFuture** [kohillyang/mx-openpose#4]
Hi,
   error message displayed when running demo.py and model_test.py. 
   the model is latest you supplied in #2.

demo.py

> [18:54:20] E:\DeepLearning\mxnet-cm39\src\nnvm\legacy_json_util.cc:190: Loa
ding symbol saved by previous version v0.12.0. Attempting to upgrade...
[18:54:20] E:\DeepLearning\mxnet-cm39\src\nnvm\legacy_json_util.cc:198: Sym
bol successfully upgraded!
set([])
set(['data'])
demo.py:115: RuntimeWarning: invalid value encountered in divide
  vec = np.divide(vec, norm)
demo.py:134: RuntimeWarning: invalid value encountered in greater
  criterion1 = len(np.nonzero(score_midpts > param['thre2'])[0]) > 0.8 * len(sco
re_midpts)
Traceback (most recent call last):
  File "demo.py", line 358, in <module>
    main(args.images,args.prefix,args.epoch)
  File "demo.py", line 347, in main
    parse_heatpaf(oriImg,heatmap_avg,paf_avg)
  File "demo.py", line 261, in parse_heatpaf
    cv2.circle(img_ori,coo,3,colors[n],thickness = 3,)
IndexError: list index out of range

model_test.py

>  [18:30:22] e:work\deeplearning\mxnet-cm39\src\operator\tensor\../elemwise_op_c
ommon.h:122: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node
at 0-th output: expected [128,169,7,7], got [128,553,7,7]
Traceback (most recent call last):
  File "model_test.py", line 20, in <module>
    model.init_params(arg_params=newargs, aux_params=aux_args, allow_missing=Fal
se,allow_extra=False)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\module\modul
e.py", line 300, in init_params
    _impl(desc, arr, arg_params)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\module\modul
e.py", line 288, in _impl
    cache_arr.copyto(arr)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\ndarray\ndar
ray.py", line 1842, in copyto
    return _internal._copyto(self, out=other)
  File "<string>", line 25, in _copyto
  File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\_ctypes\ndar
ray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\base.py", li
ne 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:30:22] e:work\deeplearning\mxnet-cm39\src\operator\t
ensor\../elemwise_op_common.h:122: Check failed: assign(&dattr, (*vec)[i]) Incom
patible attr in node  at 0-th output: expected [128,169,7,7], got [128,553,7,7]

**Comment by kohillyang** [comment]
I'll recheck that tonight, thansk for your issue.

At 2017-11-21 18:34:38, "goodtogood" <notifications@github.com> wrote:


Hi,
error message displayed when running model_test.py. the model is latest you supplied in #2

[18:30:22] e:work\deeplearning\mxnet-cm39\src\operator\tensor../elemwise_op_c
ommon.h:122: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node
at 0-th output: expected [128,169,7,7], got [128,553,7,7]
Traceback (most recent call last):
File "model_test.py", line 20, in
model.init_params(arg_params=newargs, aux_params=aux_args, allow_missing=Fal
se,allow_extra=False)
File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\module\modul
e.py", line 300, in init_params
_impl(desc, arr, arg_params)
File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\module\modul
e.py", line 288, in _impl
cache_arr.copyto(arr)
File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\ndarray\ndar
ray.py", line 1842, in copyto
return _internal._copyto(self, out=other)
File "", line 25, in _copyto
File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet_ctypes\ndar
ray.py", line 92, in _imperative_invoke
ctypes.byref(out_stypes)))
File "D:\Anaconda2\lib\site-packages\mxnet-0.12.1-py2.7.egg\mxnet\base.py", li
ne 146, in check_call
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:30:22] e:work\deeplearning\mxnet-cm39\src\operator\t
ensor../elemwise_op_common.h:122: Check failed: assign(&dattr, (*vec)[i]) Incom
patible attr in node at 0-th output: expected [128,169,7,7], got [128,553,7,7]

**Comment by kohillyang** [comment]
I have no problem using the model i uploaded, could you provide your sha1sum?
you can use command `sha1sum yks_pose-8600.params ` to get it.

my result is 23b994c90c7b8c39e3dbcd65d0143a615327bc08

**Comment by kohillyang** [comment]
http://pan.baidu.com/s/1i5H2WHB

**Comment by kohillyang** [comment]
And Please Make sure you are using the latest code.

**Comment by BackT0TheFuture** [comment]
@kohillyang  
sorry for my mistakes.  It works now .
thank you so much !
